const Razorpay = require('razorpay');
const crypto = require('crypto');
const env = require('../config/env');
const ApiError = require('../utils/apiError');
const { info, error: logError } = require('../utils/logger');

let razorpayInstance = null;

/**
 * Singleton getter for Razorpay instance
 */
const getRazorpayInstance = () => {
  if (!razorpayInstance) {
    if (!env.razorpayKeyId || !env.razorpayKeySecret) {
      // Defer throwing until the service is actually invoked to prevent startup crashes if only using Stripe
      throw new Error('Razorpay credentials (RAZORPAY_KEY_ID or RAZORPAY_KEY_SECRET) are missing from environment variables');
    }
    razorpayInstance = new Razorpay({
      key_id: env.razorpayKeyId,
      key_secret: env.razorpayKeySecret
    });
  }
  return razorpayInstance;
};

const razorpayService = {
  /**
   * Creates an Order in Razorpay
   */
  async createOrder(amount, currency = 'INR', receiptId, metadata = {}) {
    try {
      const rzp = getRazorpayInstance();
      
      // Amount must be in smallest currency unit (paise for INR)
      const amountInSmallestUnit = Math.round(amount);

      const options = {
        amount: amountInSmallestUnit,
        currency: currency.toUpperCase(),
        receipt: receiptId,
        notes: metadata
      };

      const order = await rzp.orders.create(options);

      info(`Razorpay Order created: [${order.id}] for receipt [${receiptId}]`);

      return {
        id: order.id,
        // Razorpay does not use a client_secret like Stripe, frontend uses order.id
        client_secret: null, 
        amount: order.amount,
        currency: order.currency,
        status: order.status, // e.g., 'created'
        gateway: 'razorpay'
      };
    } catch (err) {
      logError(`Razorpay createOrder Error: ${err.message}`);
      throw new ApiError(500, `Failed to initialize Razorpay payment: ${err.message}`);
    }
  },

  /**
   * Verifies the payment signature generated by Razorpay SDK on the frontend
   */
  async verifyPayment(paymentData) {
    try {
      const { razorpay_order_id, razorpay_payment_id, razorpay_signature } = paymentData;

      if (!razorpay_order_id || !razorpay_payment_id || !razorpay_signature) {
        throw new ApiError(400, 'Missing Razorpay signature verification parameters');
      }

      const body = razorpay_order_id + "|" + razorpay_payment_id;

      const expectedSignature = crypto
        .createHmac('sha256', env.razorpayKeySecret)
        .update(body.toString())
        .digest('hex');

      const isAuthentic = expectedSignature === razorpay_signature;

      if (!isAuthentic) {
        logError(`Razorpay Signature Mismatch. Expected: ${expectedSignature}, Received: ${razorpay_signature}`);
        throw new ApiError(400, 'Invalid Payment Signature');
      }

      // Explicitly fetch the payment details from Razorpay to confirm status and amount
      const rzp = getRazorpayInstance();
      const paymentDetails = await rzp.payments.fetch(razorpay_payment_id);

      let mappedStatus = 'PENDING';
      if (paymentDetails.status === 'captured') mappedStatus = 'PAID';
      if (paymentDetails.status === 'authorized') mappedStatus = 'AUTHORIZED';
      if (paymentDetails.status === 'failed') mappedStatus = 'FAILED';
      if (paymentDetails.status === 'refunded') mappedStatus = 'REFUNDED';

      return {
        verified: true,
        id: paymentDetails.id,
        order_id: paymentDetails.order_id,
        status: mappedStatus,
        amount: paymentDetails.amount,
        currency: paymentDetails.currency,
        raw_status: paymentDetails.status
      };
    } catch (err) {
      logError(`Razorpay verifyPayment Error: ${err.message}`);
      throw new ApiError(500, `Failed to verify payment with Razorpay: ${err.message}`);
    }
  },

  /**
   * Captures an authorized payment (if manual capture is configured)
   */
  async capturePayment(paymentId, amountToCapture) {
    try {
      const rzp = getRazorpayInstance();
      const amountInPaise = Math.round(amountToCapture);
      
      const captureResult = await rzp.payments.capture(paymentId, amountInPaise, 'INR');
      
      info(`Razorpay Payment captured: [${captureResult.id}]`);
      return captureResult;
    } catch (err) {
      logError(`Razorpay capturePayment Error: ${err.message}`);
      throw new ApiError(500, `Failed to capture payment: ${err.message}`);
    }
  },

  /**
   * Processes a full or partial refund
   */
  async refundPayment(paymentId, amount = null, metadata = {}) {
    try {
      const rzp = getRazorpayInstance();
      const refundOptions = {
        notes: metadata
      };

      if (amount) {
        refundOptions.amount = Math.round(amount);
      }

      const refund = await rzp.payments.refund(paymentId, refundOptions);

      info(`Razorpay Refund initiated: [${refund.id}] for Payment [${paymentId}]`);
      
      return {
        id: refund.id,
        status: refund.status, // e.g., 'processed', 'pending', 'failed'
        amount: refund.amount,
        payment_id: paymentId
      };
    } catch (err) {
      logError(`Razorpay refundPayment Error: ${err.message}`);
      throw new ApiError(500, `Refund failed: ${err.message}`);
    }
  },

  /**
   * Retrieves full details of a specific Payment
   */
  async getPaymentDetails(paymentId) {
    try {
      const rzp = getRazorpayInstance();
      const payment = await rzp.payments.fetch(paymentId);
      return payment;
    } catch (err) {
      logError(`Razorpay getPaymentDetails Error: ${err.message}`);
      throw new ApiError(404, 'Payment details not found');
    }
  },

  /**
   * Retrieves a list of recent Payments (History)
   */
  async getPaymentHistory(limit = 10, skip = 0) {
    try {
      const rzp = getRazorpayInstance();
      const payments = await rzp.payments.all({ count: limit, skip });
      return payments.items;
    } catch (err) {
      logError(`Razorpay getPaymentHistory Error: ${err.message}`);
      throw new ApiError(500, 'Failed to retrieve payment history from Razorpay');
    }
  },

  /**
   * Validates the cryptographic signature of incoming Razorpay Webhooks
   */
  validateWebhookSignature(payloadBody, signatureHeader) {
    try {
      if (!env.razorpayWebhookSecret) {
        throw new Error('Razorpay Webhook Secret is missing from environment variables');
      }

      // Razorpay validates against the raw stringified body payload
      const expectedSignature = crypto
        .createHmac('sha256', env.razorpayWebhookSecret)
        .update(payloadBody)
        .digest('hex');

      if (expectedSignature !== signatureHeader) {
        throw new Error('Webhook Signature Verification Failed');
      }

      return true;
    } catch (err) {
      logError(`Razorpay Signature Validation Failed: ${err.message}`);
      throw new ApiError(400, `Webhook Signature Verification Failed: ${err.message}`);
    }
  },

  /**
   * Handles and routes webhook events based on their type
   * @param {string} payloadBody - The raw stringified request body
   * @param {string} signatureHeader - The 'x-razorpay-signature' header
   */
  async handleWebhook(payloadBody, signatureHeader) {
    try {
      this.validateWebhookSignature(payloadBody, signatureHeader);
      
      const event = JSON.parse(payloadBody);

      let result = {
        handled: true,
        type: event.event,
        paymentId: null,
        orderId: null,
        status: null
      };

      const paymentEntity = event.payload.payment?.entity;

      switch (event.event) {
        case 'payment.captured':
          info(`Webhook Event: Payment [${paymentEntity.id}] captured.`);
          result.paymentId = paymentEntity.id;
          result.orderId = paymentEntity.order_id;
          result.status = 'PAID';
          break;
        case 'payment.failed':
          info(`Webhook Event: Payment [${paymentEntity.id}] failed.`);
          result.paymentId = paymentEntity.id;
          result.orderId = paymentEntity.order_id;
          result.status = 'FAILED';
          break;
        case 'refund.processed':
          const refundEntity = event.payload.refund?.entity;
          info(`Webhook Event: Refund [${refundEntity.id}] processed.`);
          result.paymentId = refundEntity.payment_id;
          // You'd ideally check if the refund was partial or full, for now returning REFUNDED
          result.status = 'REFUNDED'; 
          break;
        default:
          info(`Webhook Event: Unhandled event type [${event.event}]`);
          result.handled = false;
      }

      return result;
    } catch (err) {
      logError(`Razorpay handleWebhook Error: ${err.message}`);
      throw err;
    }
  }
};

module.exports = razorpayService;
